"""Emit manuscript/numbers.tex: every quantity the prose quotes, as a LaTeX macro.

The manuscript previously transcribed results into the prose by hand. When the
evaluation was re-run, twenty-one prose values silently kept their old figures
while the tables were regenerated, so the paper stated its headline result twice
with different numbers. Macros make that impossible: the prose and the tables read
the same JSON, and a re-run updates both.

    python manuscript/make_numbers.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "numbers.tex"

F = json.loads((ROOT / "real_data" / "results_fused.json").read_text())
C = json.loads((ROOT / "real_data" / "results_ceiling_per_corpus.json").read_text())
Q = json.loads((ROOT / "real_data" / "results_quantisation.json").read_text())
A = json.loads((ROOT / "real_data" / "results_signal_ablation.json").read_text())
P = json.loads((ROOT / "real_data" / "results_corpus.json").read_text())
L = json.loads((ROOT / "real_data" / "results_longhorizon.json").read_text())
D = json.loads((ROOT / "real_data" / "results_distributions.json").read_text())
_ts = ROOT / "real_data" / "results_taskshield.json"
TS = json.loads(_ts.read_text()) if _ts.exists() else None

METHOD = "SENTRY-Fuse (S3+S4)"
lines = ["% Generated by manuscript/make_numbers.py -- do not edit by hand.",
         "% Every value below is read from real_data/results_*.json.", ""]


def mac(name: str, value: str) -> None:
    lines.append("\\newcommand{\\%s}{%s}" % (name, value))


def blk(corpus):
    return F["pooled"] if corpus == "Pooled" else F["corpora"][corpus]


def num(x, dp=3):
    return f"{x:.{dp}f}"


SHORT = {"GPT-4o-mini": "Gpt", "DeepSeek": "Ds", "Pooled": "Pool"}
DET = {"S3 instruction only": "Sthree", "S4 audit only": "Sfour",
       "S5 provenance only": "Sfive", "S1 transition only": "Sone",
       "S2 novelty only": "Stwo", "S1 + S2 behavioural": "Behav",
       METHOD: "Fuse", "S3+S4+S5 (adds provenance)": "FuseP",
       "all five signals": "AllFive"}

for corpus, cs in SHORT.items():
    b = blk(corpus)
    mac(f"n{cs}Comp", str(b["n_compromised"]))
    mac(f"n{cs}Neg", str(b["n_test"]))
    mac(f"n{cs}Benign", str(b["n_benign"]))
    for det, ds in DET.items():
        d = b["detectors"][det]
        mac(f"{cs}{ds}Auroc", num(d["auroc_mean"]))
        mac(f"{cs}{ds}AurocSd", num(d["auroc_std"]))
        mac(f"{cs}{ds}Tpr", num(d["tpr_at_0.05_mean"]))
        mac(f"{cs}{ds}TprSd", num(d["tpr_at_0.05_std"]))
        mac(f"{cs}{ds}Fpr", f"{d['realised_fpr_at_0.05'] * 100:.1f}")
        mac(f"{cs}{ds}TprLow", num(d["tpr_at_0.0366_mean"]))
        mac(f"{cs}{ds}FprLow", f"{d['realised_fpr_at_0.0366'] * 100:.1f}")

# four-way (out-of-sample operating point)
fw = F["pooled_four_way"]
mac("nPoolFourNeg", str(fw["n_test"]))
for det, ds in (("S3 instruction only", "Sthree"), (METHOD, "Fuse")):
    d = fw["detectors"][det]
    mac(f"Four{ds}Auroc", num(d["auroc_mean"]))
    mac(f"Four{ds}Tpr", num(d["tpr_at_0.05_mean"]))
    mac(f"Four{ds}TprSd", num(d["tpr_at_0.05_std"]))
    mac(f"Four{ds}Fpr", f"{d['realised_fpr_at_0.05'] * 100:.1f}")

# bootstrap CIs
for tag, ms in (("s3s4_minus_s3_auroc", "GainAuroc"),
                ("s3s4_minus_s3_tpr", "GainTpr"),
                ("s5_contribution_auroc", "SfiveAuroc"),
                ("s5_contribution_tpr", "SfiveTpr")):
    r = F["bootstrap"][tag]
    mac(f"Boot{ms}", f"{r['mean']:+.4f}".replace("+", "+"))
    mac(f"Boot{ms}Lo", f"{r['ci_lo']:+.4f}")
    mac(f"Boot{ms}Hi", f"{r['ci_hi']:+.4f}")
    mac(f"Boot{ms}P", f"{r['p_le_zero']:.3f}")
    mac(f"Boot{ms}Sd", f"{r['sd']:.4f}")

# how often S3 collapses to zero recall across splits
z = sum(1 for v in blk("Pooled")["detectors"]["S3 instruction only"]["tpr_at_0.05_per_seed"]
        if v == 0.0)
mac("SthreeZeroSplits", str(z))
mac("nSeeds", str(F["n_seeds"]))

# evidence channels
for corpus, cs in (("GPT-4o-mini", "Gpt"), ("DeepSeek", "Ds")):
    r = C["corpora"][corpus]
    mac(f"Ev{cs}Perm", num(r["payload_visible_in_trace"]["frac"]))
    mac(f"Ev{cs}Strict", num(r["payload_visible_strict"]["frac"]))
    mac(f"Ev{cs}Sink", num(r["has_effectful_sink_call"]["frac"]))
r = C["pooled"]
mac("EvPoolPerm", num(r["payload_visible_in_trace"]["frac"]))
mac("EvPoolStrict", num(r["payload_visible_strict"]["frac"]))
mac("EvPoolSink", num(r["has_effectful_sink_call"]["frac"]))
mac("EvPoolFull", num(r["core_fully_visible"]["frac"]))
mac("NuPerm", num(r["primary"]["nu"]))
mac("NuStrict", num(r["strict"]["nu"]))
mac("NuFull", num(r["full_directive"]["nu"]))
mac("BoundFull", num(r["full_directive"]["ceiling_at_alpha_0.05"]))
mac("BoundStrict", num(r["strict"]["ceiling_at_alpha_0.05"]))
for k, w in (("5", "Five"), ("10", "Ten"), ("20", "Twenty"), ("30", "Thirty")):
    mac(f"EvCoreK{w}", num(r["distinctive_core_visible"][k]))

# quantisation
WORD = {"5": "Five", "10": "Ten", "23": "TwentyThree", "35": "ThirtyFive",
        "47": "FortySeven", "63": "SixtyThree", "200": "TwoHundred"}
for n, w in WORD.items():
    if n in Q["by_calibration_size"]:
        mac(f"QuantN{w}", num(Q["by_calibration_size"][n]["psi_auroc"]))
mac("QuantHalf", num(Q["counterexamples"]["saturation_to_half"]["psi"]))
mac("QuantBelow", num(Q["counterexamples"]["below_half"]["psi"]))
mac("QuantBelowRaw", num(Q["counterexamples"]["below_half"]["raw"]))

# normalisation ablation
for scorer in ("lexicon", "llm"):
    for tr in ("excess_max", "conformal"):
        for fam in ("important_instr", "injecagent"):
            r = A[f"{scorer}|{tr}|{fam}"]
            tag = ("Lex" if scorer == "lexicon" else "Judge") + \
                  ("Max" if tr == "excess_max" else "Conf") + \
                  ("Imp" if fam == "important_instr" else "Inj")
            mac(f"Abl{tag}Auroc", num(r["auroc_attempt_max"]))
            mac(f"Abl{tag}Far", num(r["pac_nominal_far"], 4))

# corpus and polarity
mac("nBenign", str(P["totals"]["benign"]))
mac("nAttacks", str(P["totals"]["attacks"]))
mac("nComp", str(P["totals"]["compromised"]))
mac("nResisted", str(P["totals"]["resisted"]))
mac("PolTruePays", str(P["polarity_check"]["security_true_pays"]))
mac("PolTrueNoPay", str(P["polarity_check"]["security_true_no_pay"]))
mac("PolFalsePays", str(P["polarity_check"]["security_false_pays"]))
mac("PolFalseNoPay", str(P["polarity_check"]["security_false_no_pay"]))
mac("PolTotal", str(sum(P["polarity_check"].values())))

# long horizon
M = L["methods"]
for key, ms in (("SENTRY (alpha=0.2)", "EdTwo"), ("SENTRY (alpha=0.05)", "EdFive"),
                ("fixed threshold (q=0.95)", "FixQnf"),
                ("fixed threshold (q=0.999)", "FixQnnn")):
    mac(f"Lh{ms}Fa", f"{M[key]['false_alarms_per_1k']:.1f}")
    mac(f"Lh{ms}Det", num(M[key]["attack_detection"]))

# distributional statistics motivating Propositions 1 and 2
mac("BenIlMedian", num(D["benign_instruction_likeness"]["median"]))
mac("BenIlMean", num(D["benign_instruction_likeness"]["mean"]))
mac("BenIlMax", num(D["benign_instruction_likeness"]["max"]))
mac("InjIlMax", num(D["injecagent_instruction_likeness"]["max"]))
mac("SfourSatPct", f"{D['s4_saturates_at_one']['pct']:.1f}")
mac("SfourSatN", str(D["s4_saturates_at_one"]["n"]))

# Task Shield baseline, re-implemented on our corpus
mac("TaskShieldReady", "1" if TS is not None else "0")
if TS is not None:
    for corpus, cs in (("GPT-4o-mini", "Gpt"), ("DeepSeek", "Ds"), ("Pooled", "Pool")):
        r = TS["pooled"] if corpus == "Pooled" else TS["corpora"][corpus]
        mac(f"Ts{cs}Auroc", num(r["auroc"]))
        mac(f"Ts{cs}RuleTpr", num(r["rule_tpr"]))
        mac(f"Ts{cs}RuleFpr", num(r["rule_fpr"]))
        mac(f"Ts{cs}Tpr", num(r["tpr_at_0.05_mean"]))
        mac(f"Ts{cs}TprSd", num(r["tpr_at_0.05_std"]))
        mac(f"Ts{cs}Fpr", f"{r['realised_fpr_at_0.05'] * 100:.1f}")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} with {sum(1 for l in lines if l.startswith(chr(92) + 'newcommand'))} macros")
